services:
  irc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt/live/irc.clesucre.fr:/app/ssl
    ports:
      - "${IRC_PORT}:6667"
    environment:
      - IRC_PASSWORD=${IRC_PASSWORD}
      - ENABLE_SSL=${ENABLE_SSL}
    tty: true
    working_dir: /app
