services:
  irc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./irc:/app
      - /etc/letsencrypt/live/irc.clesucre.fr:/app/ssl
    ports:
      - "6667:6667"
    tty: true
    working_dir: /app
